# zeros

In [1]:
import numpy as np

In [2]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [3]:
arr.ndim

1

In [4]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# ones

In [5]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [6]:
import numpy as np
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# eye

In [10]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# digonal fun

In [12]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
rand_arr = np.random.randint(1,100,20).reshape(2,2,5)
rand_arr

array([[[52, 28, 54, 75, 40],
        [19,  8, 93, 63, 96]],

       [[68, 81, 62, 42, 17],
        [47, 58, 89,  9, 79]]])

In [17]:
rand_arr = np.random.rand(10)
rand_arr

array([0.12526047, 0.2946181 , 0.45692476, 0.37267596, 0.63845632,
       0.21492798, 0.38009436, 0.89390165, 0.67120627, 0.9415188 ])

In [18]:
rand_arr = np.random.rand(3,3) # o/p between 0---1
rand_arr

array([[0.85461727, 0.82397766, 0.94484058],
       [0.61787485, 0.26558632, 0.35500983],
       [0.13015581, 0.81555453, 0.57222671]])

In [19]:
rand_arr = np.random.randn(40)# centered between - 0 +
rand_arr

array([-0.18189985,  0.09417488,  0.42501837, -1.12689464, -2.25275223,
       -0.03185218, -1.58709628,  0.94986532, -0.90914227,  0.96570082,
       -1.30328887,  1.42080404, -0.12928932,  2.26040982, -2.02833152,
       -0.73086738, -0.34620055, -0.07739883,  2.09714689, -0.10978787,
       -0.00929032, -1.71929158,  0.26052425,  0.26024689, -0.21873358,
        0.79901192,  0.31276781, -1.02186193,  1.14386439, -0.18570084,
        0.22891465,  0.21782415, -0.93549866, -0.6672831 , -0.24925311,
       -0.89866969,  0.62326522,  1.31257675,  0.49964341,  0.02715582])

In [20]:
rand_arr = np.random.randn(40)# mean will be near to zero
np.mean(rand_arr)

-0.16355870551141266

In [21]:
rand_arr = np.random.randn(150)# mean will be near to zero
np.mean(rand_arr)

-0.003182021085495661