In [1]:
import numpy as np

# two bracket notation

In [2]:
matrix = np.array ([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [3]:
matrix [1][2]

30

In [4]:
matrix[1][1]

25

# single bracket notation

In [5]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
matrix[2,1]

40

In [7]:
matrix[2,0]

35

# slicing using single bracket notation

In [8]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
matrix[:,:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [11]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [12]:
matrix[3:,3:]

array([], shape=(0, 0), dtype=int32)

In [13]:
matrix2 = np.random.randint(1,101,80).reshape(8,10)
matrix2

array([[ 38,  15,   9,  74,  60,  24,  79,  73,  91,  79],
       [ 13,  44,   7,  30,  52,  12,  18,  65,  68,  37],
       [ 97,  97,  25,  67,  28,  21,  36,  40,  56, 100],
       [ 88,  41,  93,  11,  56, 100,  69,  47,  68,  68],
       [ 84,  73,  22,  92,  72,  75,  94,  43,   3,  67],
       [ 60,  41,  48,  61,  68,  99,  73,  87,  49,  78],
       [ 29,  83,  39,  52,  87,  27,  31,  66,   4,  39],
       [  6,  16,  47,  95,  40,  16,  97,  22,  60,  95]])

In [14]:
matrix2[5:,7:]

array([[87, 49, 78],
       [66,  4, 39],
       [22, 60, 95]])

In [15]:
matrix2[2:5,4:7]

array([[ 28,  21,  36],
       [ 56, 100,  69],
       [ 72,  75,  94]])