# indexing

In [1]:
import numpy as np

In [2]:
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [3]:
arr[0]

5

In [4]:
arr[1]

10

In [5]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [6]:

arr[-1]

25

In [7]:
arr[-4]

10

In [8]:
arr[::2]

array([ 5, 15, 25])

In [9]:
arr

array([ 5, 10, 15, 20, 25])

# slicing

In [10]:
arr[0:2]

array([ 5, 10])

In [11]:
arr[1:]

array([10, 15, 20, 25])

In [12]:
arr[:2]

array([ 5, 10])

In [13]:
arr[-3:]

array([15, 20, 25])

In [14]:
arr[:]

array([ 5, 10, 15, 20, 25])

In [15]:
arr[1:4:2]

array([10, 20])