In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
#os.chdir('C:\\Users\Hp\Desktop\\Pyt_language\\machine-learning')
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [3]:
x = df.iloc[:,2:4]
x

Age  EstimatedSalary
0     42           121315
1     53            67214
2     59           111005
3     39            53414
4     39           114285
..   ...              ...
395   20           141231
396   50            75848
397   25            82560
398   55           147667
399   54           134972

[400 rows x 2 columns]

In [4]:
x = df.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],


In [5]:
y = df.iloc[:,4]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [6]:
y.shape

(400,)

In [ ]:
y = df.iloc[:,4].values
y

In [ ]:
# Feature Scaling – Standardization (To standardize Salary)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
x

In [ ]:
x.size

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
x_train

array([[    32, 126318],
       [    52,  61880],
       [    28,  96148],
       [    58, 108578],
       [    24, 119308],
       [    52, 100654],
       [    31,  66259],
       [    43,  88766],
       [    21, 123460],
       [    38,  85428],
       [    45,  83469],
       [    57, 124533],
       [    59,  96999],
       [    36,  51894],
       [    42, 130324],
       [    53, 118544],
       [    50, 104297],
       [    29, 130705],
       [    26,  68131],
       [    30,  52952],
       [    27,  71384],
       [    47, 121827],
       [    35,  79146],
       [    35,  56687],
       [    25, 149284],
       [    28,  80299],
       [    27,  60011],
       [    21, 108656],
       [    58, 141603],
       [    44, 143222],
       [    29,  69997],
       [    58,  60780],
       [    51, 112365],
       [    43,  65553],
       [    43,  78367],
       [    37, 144858],
       [    20,  64957],
       [    42, 120639],
       [    50, 114793],
       [    44, 123166],


In [8]:
from sklearn.preprocessing import StandardScaler
x_trainsc = StandardScaler()
x_train = x_trainsc.fit_transform(x_train)


In [9]:
x_test = x_trainsc.transform(x_test)
x_test

array([[-0.34352207,  0.4301073 ],
       [-1.44788979, -0.0475162 ],
       [-0.17361935, -1.15068715],
       [-0.59837616,  1.26431571],
       [ 1.69531063, -1.2532942 ],
       [-0.5134248 , -0.021937  ],
       [ 1.52540791, -0.72001327],
       [-1.27798706,  1.0782225 ],
       [ 0.50599155,  1.77553684],
       [-0.42847344, -0.35798598],
       [-0.42847344, -1.05210746],
       [-0.08866798,  1.46024148],
       [-1.02313297, -1.35876758],
       [-1.70274388,  1.39232054],
       [-1.53284115, -1.68316986],
       [-0.34352207, -0.92014782],
       [-1.61779251, -0.81819385],
       [-0.25857071, -1.19941461],
       [ 1.01569973, -0.56033377],
       [-0.34352207, -1.68389551],
       [ 0.84579701,  0.80116895],
       [ 0.33608883,  0.89474164],
       [ 0.59094292, -0.24935602],
       [ 0.93074837,  1.69698512],
       [ 1.61035927, -0.66011078],
       [ 0.25113747,  0.29506365],
       [ 1.01569973, -1.67500629],
       [ 1.69531063,  1.84251443],
       [-0.17361935,

In [10]:
x_train.size

640

In [11]:
x_test.size

160

In [12]:
y_train.shape

(320,)

In [13]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [14]:
y_pred = logmodel.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
y_test

In [15]:
from sklearn.metrics import classification_report
print(classification_report (y_test,y_pred))

              precision    recall  f1-score   support

           0       0.66      1.00      0.80        53
           1       0.00      0.00      0.00        27

    accuracy                           0.66        80
   macro avg       0.33      0.50      0.40        80
weighted avg       0.44      0.66      0.53        80



C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y,y_pred)
print (cm)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score (y,y_pred)