In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [3]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

# horizental stacking

In [4]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

# vertical stacking

In [5]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [6]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
np.stack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])