In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix= np.random.randint(1,11,81).reshape(9,3,3)
matrix

array([[[ 3,  3,  7],
        [ 2,  4, 10],
        [ 7,  2,  1]],

       [[ 2, 10,  1],
        [ 1, 10,  4],
        [ 5,  1,  1]],

       [[ 5,  2,  8],
        [ 4,  3,  5],
        [ 8,  3,  5]],

       [[ 9,  1,  8],
        [10,  4,  5],
        [ 7,  2,  6]],

       [[ 7,  3,  2],
        [ 9,  4,  6],
        [ 1,  3,  7]],

       [[ 3,  5,  5],
        [ 7,  4,  1],
        [ 7,  5,  8]],

       [[ 7,  8,  2],
        [ 6,  8, 10],
        [ 3,  5,  9]],

       [[ 2,  3,  2],
        [ 2,  4,  6],
        [10,  1,  9]],

       [[ 2,  7,  4],
        [ 4,  6, 10],
        [ 8, 10,  3]]])

In [3]:
np.sum(matrix)

407

In [4]:
matrix.sum

<function ndarray.sum>

In [5]:
np.min(matrix)

1

In [6]:
np.max(matrix)

10

In [7]:
np.mean(matrix,axis=1)

array([[4.        , 3.        , 6.        ],
       [2.66666667, 7.        , 2.        ],
       [5.66666667, 2.66666667, 6.        ],
       [8.66666667, 2.33333333, 6.33333333],
       [5.66666667, 3.33333333, 5.        ],
       [5.66666667, 4.66666667, 4.66666667],
       [5.33333333, 7.        , 7.        ],
       [4.66666667, 2.66666667, 5.66666667],
       [4.66666667, 7.66666667, 5.66666667]])

In [8]:
np.min(matrix,axis=1)

array([[2, 2, 1],
       [1, 1, 1],
       [4, 2, 5],
       [7, 1, 5],
       [1, 3, 2],
       [3, 4, 1],
       [3, 5, 2],
       [2, 1, 2],
       [2, 6, 3]])

In [9]:
np.max(matrix,axis=1)

array([[ 7,  4, 10],
       [ 5, 10,  4],
       [ 8,  3,  8],
       [10,  4,  8],
       [ 9,  4,  7],
       [ 7,  5,  8],
       [ 7,  8, 10],
       [10,  4,  9],
       [ 8, 10, 10]])

In [10]:
np.max(matrix,axis=0)

array([[ 9, 10,  8],
       [10, 10, 10],
       [10, 10,  9]])

In [11]:
np.sum(matrix ,axis=1)

array([[12,  9, 18],
       [ 8, 21,  6],
       [17,  8, 18],
       [26,  7, 19],
       [17, 10, 15],
       [17, 14, 14],
       [16, 21, 21],
       [14,  8, 17],
       [14, 23, 17]])

# cumulative sum

In [12]:
np.cumsum(matrix)

array([  3,   6,  13,  15,  19,  29,  36,  38,  39,  41,  51,  52,  53,
        63,  67,  72,  73,  74,  79,  81,  89,  93,  96, 101, 109, 112,
       117, 126, 127, 135, 145, 149, 154, 161, 163, 169, 176, 179, 181,
       190, 194, 200, 201, 204, 211, 214, 219, 224, 231, 235, 236, 243,
       248, 256, 263, 271, 273, 279, 287, 297, 300, 305, 314, 316, 319,
       321, 323, 327, 333, 343, 344, 353, 355, 362, 366, 370, 376, 386,
       394, 404, 407], dtype=int32)

In [13]:
np.cumsum(matrix,axis=0)

array([[[ 3,  3,  7],
        [ 2,  4, 10],
        [ 7,  2,  1]],

       [[ 5, 13,  8],
        [ 3, 14, 14],
        [12,  3,  2]],

       [[10, 15, 16],
        [ 7, 17, 19],
        [20,  6,  7]],

       [[19, 16, 24],
        [17, 21, 24],
        [27,  8, 13]],

       [[26, 19, 26],
        [26, 25, 30],
        [28, 11, 20]],

       [[29, 24, 31],
        [33, 29, 31],
        [35, 16, 28]],

       [[36, 32, 33],
        [39, 37, 41],
        [38, 21, 37]],

       [[38, 35, 35],
        [41, 41, 47],
        [48, 22, 46]],

       [[40, 42, 39],
        [45, 47, 57],
        [56, 32, 49]]], dtype=int32)

In [14]:
np.prod(matrix,axis=1)

array([[ 42,  24,  70],
       [ 10, 100,   4],
       [160,  18, 200],
       [630,   8, 240],
       [ 63,  36,  84],
       [147, 100,  40],
       [126, 320, 180],
       [ 40,  12, 108],
       [ 64, 420, 120]])