In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr*2

array([2, 4, 6, 8])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr+5

array([6, 7, 8, 9])

In [6]:
arr**3

array([ 1,  8, 27, 64], dtype=int32)

In [7]:
arr= np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [9]:
arr*2

array([[2, 4],
       [6, 8]])

In [10]:
arr+5

array([[6, 7],
       [8, 9]])

In [11]:
arr**4

array([[  1,  16],
       [ 81, 256]], dtype=int32)

In [12]:
arr/1

array([[1., 2.],
       [3., 4.]])

In [13]:
arr/0

C:\Users\Abhinav\AppData\Local\Temp\ipykernel_11496\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf],
       [inf, inf]])